spring:
  profiles:
    active:
    - dev

---
server:
  port: 8768
spring: 
  profiles: dev
  application: 
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
server:
  port: 8769
spring:
  profiles: test
  application: 
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/